package com.bookstore.ui.menu;

public enum UIState {
    MAIN,
    CHANGE_ORDER_STATUS_CHOOSE,
    PRINT_ORDERS_CHOOSE_SORT,
    PRINT_REQUESTS_CHOOSE_SORT,
    PRINT_CLOSED_ORDERS_CHOOSE_SORT,
    PRINT_STALE_BOOKS_CHOOSE_SORT,
    PRINT_BOOKS_CHOOSE_SORT
}
